AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Grocery Restocking System"

Resources:
  GroceryEventsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "GroceryEvents"
      AttributeDefinitions:
        - AttributeName: "EventId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "EventId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES # Enabling DynamoDB Stream on the table

  GroceryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GroceryList
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: Name
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: NameIndex
          KeySchema:
            - AttributeName: Name
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  PantryItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PantryItems
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  GroceryEventsQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "GroceryEventsQueue"
      VisibilityTimeout: 70

  GroceryRestockNotificationsTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: "GroceryRestockNotifications"

  GrocerySNSEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref GroceryRestockNotificationsTopic
      Protocol: email
      Endpoint: asma.mahmuda@outlook.com

  EventPublisher:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: EventPublisher::EventPublisher.EventPublisher::FunctionHandler
      Runtime: dotnet8
      CodeUri: ./src/EventPublisher
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          GROCERY_EVENTS_TABLE: !Ref GroceryEventsTable
          GROCERY_TABLE: !Ref GroceryTable
          SQS_QUEUE_URL: !Ref GroceryEventsQueue
      Events:
        DynamoDBStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt GroceryEventsTable.StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 5
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GroceryEventsTable
        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt GroceryEventsQueue.Arn
  EventProcessor:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: EventProcessor::EventProcessor.EventProcessor::FunctionHandler
      Runtime: dotnet8
      CodeUri: ./src/EventProcessor
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          GROCERY_EVENTS_TABLE: !Ref GroceryEventsTable
          GROCERY_TABLE: !Ref GroceryTable
          PANTRY_ITEMS_TABLE: !Ref PantryItemsTable
          SQS_QUEUE_URL: !Ref GroceryEventsQueue
          SNS_TOPIC_ARN: !Ref GroceryRestockNotificationsTopic
      Events:
        SQSQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt GroceryEventsQueue.Arn
            BatchSize: 10

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GroceryTable
        - DynamoDBReadPolicy:
            TableName: !Ref GroceryEventsTable
        - DynamoDBReadPolicy:
            TableName: !Ref PantryItemsTable
        - SNSPublishMessagePolicy:
            TopicName: !Ref GroceryRestockNotificationsTopic

  GroceryRestockingApi:
    Type: "AWS::Serverless::Api"
    Properties:
      Name: "GroceryRestockingApi"
      StageName: "prod"
      Cors:
        AllowMethods: "'GET,POST,PUT,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
            gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization'"
        DEFAULT_5XX:
          ResponseParameters:
            gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
            gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization'"
        BAD_REQUEST_BODY:
          ResponseParameters:
            gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
            gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization'"
        BAD_REQUEST_PARAMETERS:
          ResponseParameters:
            gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
            gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization'"
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "Grocery Restocking API"
          version: "1.0"
        paths:
          /consume-item:
            options:
              summary: "CORS preflight for consume-item"
              operationId: "consumeItemOptions"
              responses:
                "200":
                  description: "CORS preflight response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Headers:
                      type: string
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                httpMethod: "OPTIONS"
                uri: !Sub "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${ApiConsumeItemFunction.Arn}/invocations"
                passthroughBehavior: "when_no_match"
            post:
              summary: "Trigger an event for consumed item restocking"
              operationId: "consumeItem"
              parameters:
                - in: body
                  name: item
                  description: "Item information"
                  required: true
                  schema:
                    type: object
                    properties:
                      itemId:
                        type: string
                      itemName:
                        type: string
              responses:
                "200":
                  description: "Item consumption event triggered"
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Headers:
                      type: string
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                httpMethod: "POST"
                uri: !Sub "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${ApiConsumeItemFunction.Arn}/invocations"
                passthroughBehavior: "when_no_match"

  # API Gateway Lambda integration
  ApiConsumeItemFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: ApiConsumeItem::ApiConsumeItem.ApiConsumeItem::FunctionHandler
      Runtime: dotnet8
      CodeUri: ./src/ApiConsumeItem
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref GroceryEventsQueue
          OUTBOX_TABLE_NAME: !Ref GroceryEventsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GroceryEventsTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref GroceryRestockingApi
            Path: /consume-item
            Method: post
        ApiOptions:
          Type: Api
          Properties:
            RestApiId: !Ref GroceryRestockingApi
            Path: /consume-item
            Method: OPTIONS

  AddItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/AddItemFunction
      Handler: AddItemFunction::AddItemFunction.AddItemFunction::FunctionHandler
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 256
      Timeout: 10
      Environment:
        Variables:
          PANTRY_ITEMS_TABLE: !Ref PantryItemsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PantryItemsTable
      Events:
        AddItemAPI:
          Type: Api
          Properties:
            Path: /items
            Method: POST
            RestApiId: !Ref GroceryRestockingApi
        AddItemOptionsAPI:
          Type: Api
          Properties:
            Path: /items
            Method: OPTIONS
            RestApiId: !Ref GroceryRestockingApi
  UpdateStockFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: UpdateStockFunction::UpdateStockFunction.UpdateStockFunction::FunctionHandler
      Runtime: dotnet8
      CodeUri: ./src/UpdateStockFunction
      MemorySize: 256
      Timeout: 10
      Environment:
        Variables:
          GROCERY_TABLE: !Ref GroceryTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GroceryTable
      Events:
        UpdateStockAPI:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: PUT
            RestApiId: !Ref GroceryRestockingApi
        UpdateStockOptionsAPI:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: OPTIONS
            RestApiId: !Ref GroceryRestockingApi

Outputs:
  GroceryRestockingApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${GroceryRestockingApi}.execute-api.us-east-1.amazonaws.com/prod/consume-item"
